{"task_id": 105, "prediction_id": 0, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url.netloc.startswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nAttributeError: 'str' object has no attribute 'netloc'\n", "passed": false}
{"task_id": 105, "prediction_id": 1, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 2, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url.netloc.endswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nAttributeError: 'str' object has no attribute 'netloc'\n", "passed": false}
{"task_id": 105, "prediction_id": 3, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 4, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 5, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 6, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url.netloc.endswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nAttributeError: 'str' object has no attribute 'netloc'\n", "passed": false}
{"task_id": 105, "prediction_id": 7, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    if not domains:\n        return False\n    return any(url.netloc.startswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 184, in <module>\n  File \"<string>\", line 183, in test_0\n  File \"<string>\", line 38, in url_is_from_any_domain\n  File \"<string>\", line 38, in <genexpr>\nAttributeError: 'str' object has no attribute 'netloc'\n", "passed": false}
{"task_id": 105, "prediction_id": 8, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url.netloc.endswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nAttributeError: 'str' object has no attribute 'netloc'\n", "passed": false}
{"task_id": 105, "prediction_id": 9, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 10, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url.netloc.endswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nAttributeError: 'str' object has no attribute 'netloc'\n", "passed": false}
{"task_id": 105, "prediction_id": 11, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url.netloc.endswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nAttributeError: 'str' object has no attribute 'netloc'\n", "passed": false}
{"task_id": 105, "prediction_id": 12, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 13, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 14, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 15, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    if not isinstance(url, ParseResult):\n        url = urlparse(url)\n    return any(url.netloc.endswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 223, in <module>\n  File \"<string>\", line 222, in test_12\nAssertionError\n", "passed": false}
{"task_id": 105, "prediction_id": 16, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 17, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 18, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url.netloc.startswith(d) for d in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nAttributeError: 'str' object has no attribute 'netloc'\n", "passed": false}
{"task_id": 105, "prediction_id": 19, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 20, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 21, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 22, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url.netloc.endswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nAttributeError: 'str' object has no attribute 'netloc'\n", "passed": false}
{"task_id": 105, "prediction_id": 23, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 24, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 25, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 26, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url.netloc.endswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nAttributeError: 'str' object has no attribute 'netloc'\n", "passed": false}
{"task_id": 105, "prediction_id": 27, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 28, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url.netloc.startswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nAttributeError: 'str' object has no attribute 'netloc'\n", "passed": false}
{"task_id": 105, "prediction_id": 29, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 30, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url.hostname.endswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nAttributeError: 'str' object has no attribute 'hostname'\n", "passed": false}
{"task_id": 105, "prediction_id": 31, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 32, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 33, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url.hostname.endswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nAttributeError: 'str' object has no attribute 'hostname'\n", "passed": false}
{"task_id": 105, "prediction_id": 34, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 35, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url.netloc.endswith(domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nAttributeError: 'str' object has no attribute 'netloc'\n", "passed": false}
{"task_id": 105, "prediction_id": 36, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 37, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 38, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 39, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 40, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 41, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 42, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 43, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 44, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 45, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 46, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 47, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 48, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
{"task_id": 105, "prediction_id": 49, "generation": "def url_is_from_any_domain(url, domains):\n    \"\"\"Return True if the url belongs to any of the given domains\"\"\"\n    return any(url_is_from_domain(url, domain) for domain in domains)\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 182, in <module>\n  File \"<string>\", line 181, in test_0\n  File \"<string>\", line 36, in url_is_from_any_domain\n  File \"<string>\", line 36, in <genexpr>\nNameError: name 'url_is_from_domain' is not defined. Did you mean: 'url_is_from_any_domain'?\n", "passed": false}
